check = "/c/home/check"
getBrandList = "/public/fun/getBrandList"
getFRegionList = "/public/fun/getFRegionList"
getShopListAll = "/waimaiShop/shop/getShopListAll?auto_receive_order=-1&business_status=-1&docking_status=-1&iscompound=-1&limit=10&page=1&searchIds=1&searchName=&source=-1&status=1,0"
editship = "/waimaiShop/shop/editShop"
loadshop_param = "/waimaiShop/shop_param/load?mcode={0}&sid={1}&type=3"
saveConfigStore = "/waimaiShop/shop_param/saveConfigStore?type=3&sid={0}&mcode={1}"